# Generated by Django 4.1.6 on 2023-02-17 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('purchased', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='blank_img.jpg', upload_to='image_uploads', verbose_name='')),
                ('image2', models.ImageField(default='blank_img.jpg', upload_to='image_uploads', verbose_name='')),
                ('image3', models.ImageField(default='blank_img.jpg', upload_to='image_uploads', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(default='normal', max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_name')),
                ('product_stock_amount', models.IntegerField(verbose_name='stock')),
                ('product_prize', models.IntegerField(verbose_name='prize')),
                ('product_text', models.TextField(verbose_name='')),
                ('product_available', models.BooleanField(verbose_name='')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.images', verbose_name='')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('card_number', models.CharField(max_length=50, null=True, verbose_name='')),
                ('expire_date', models.DateField(null=True, verbose_name='')),
                ('cvv', models.IntegerField(null=True, verbose_name='')),
                ('upi_id', models.CharField(max_length=50, null=True, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='')),
                ('date', models.DateField(auto_now=True, verbose_name='')),
                ('payment_type', models.ForeignKey(default='cod', on_delete=django.db.models.deletion.CASCADE, to='store.payment_method', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created', models.DateTimeField(auto_now=True, verbose_name='')),
                ('order_modified', models.DateField(auto_now_add=True, verbose_name='')),
                ('paid', models.BooleanField(verbose_name='')),
                ('cart', models.ManyToManyField(to='store.cart', verbose_name='')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.payment', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
