# Generated by Django 4.1.6 on 2023-03-18 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('purchased', models.BooleanField(default=False, verbose_name='')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('discount', models.IntegerField(verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(default='normal', max_length=50, verbose_name='')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_name')),
                ('product_stock_amount', models.IntegerField(verbose_name='stock')),
                ('product_prize', models.IntegerField(verbose_name='prize')),
                ('product_text', models.TextField(verbose_name='')),
                ('product_available', models.BooleanField(verbose_name='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='')),
                ('product_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50, null=True, verbose_name='')),
                ('payment_id', models.CharField(max_length=50, null=True, verbose_name='')),
                ('date', models.DateField(auto_now=True, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('wallet_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.wallet', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('order_modified', models.DateField(auto_now=True, verbose_name='')),
                ('paid', models.BooleanField(verbose_name='')),
                ('order_processed', models.BooleanField(default=False, verbose_name='')),
                ('status', models.CharField(choices=[('0', 'Requested for Cancel'), ('1', 'Waiting to accept order'), ('2', 'Order is being Prepared'), ('3', 'Ready to Ship'), ('4', 'Out for delivery'), ('5', 'Done'), ('6', 'Cancelled'), ('7', 'Order Refused')], default='1', max_length=20)),
                ('cart', models.ManyToManyField(related_name='cart', to='store.cart', verbose_name='')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon', verbose_name='')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address', verbose_name='')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.payment', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='blank_img.jpg', upload_to='image_uploads', verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
