# Generated by Django 4.1.6 on 2023-02-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default='unknows', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.category', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.size', verbose_name=''),
        ),
    ]
