# Generated by Django 4.1.6 on 2023-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_processed',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
