# Generated by Django 4.1.6 on 2023-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Payment_method',
        ),
    ]
