# Generated by Django 4.1.6 on 2023-02-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_created',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
    ]
