# Generated by Django 4.1.6 on 2023-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_modified',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
    ]
