# Generated by Django 4.1.6 on 2023-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_order_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('step1', 'Waiting to accept order'), ('step2', 'Preparing Your order'), ('step3', 'Packing'), ('step4', 'Out for delivery')], default='step1', max_length=20),
        ),
    ]
