# Generated by Django 4.1.6 on 2023-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Waiting to accept order'), ('2', 'Preparing Your order'), ('3', 'Packing'), ('4', 'Out for delivery')], default='0', max_length=20),
        ),
    ]
