# Generated by Django 4.1.6 on 2023-03-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_coupon_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Waiting to accept order'), ('2', 'Order is being Prepared'), ('3', 'Ready to Ship'), ('4', 'Out for delivery'), ('5', 'Done'), ('0', 'Requested for Cancel')], default='1', max_length=20),
        ),
    ]
