# Generated by Django 4.1.6 on 2023-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_payment_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Waiting to accept order'), ('2', 'Order is being Prepared'), ('3', 'Ready to Ship'), ('4', 'Out for delivery'), ('5', 'Done'), ('6', 'Cancelled'), ('0', 'Requested for Cancel')], default='1', max_length=20),
        ),
    ]
