# Generated by Django 4.1.6 on 2023-03-18 11:22

import customer.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=13)),
                ('phone_number_verified', models.BooleanField(default=False, verbose_name='')),
                ('otp', models.IntegerField(default=0, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('blocked', models.BooleanField(default=False, verbose_name='')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', customer.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50, verbose_name='')),
                ('building_number', models.CharField(max_length=50, verbose_name='')),
                ('street_name', models.CharField(max_length=50, verbose_name='')),
                ('city', models.CharField(max_length=50, verbose_name='')),
                ('pin_number', models.IntegerField(verbose_name='')),
                ('phone_number', models.CharField(max_length=50, verbose_name='')),
                ('disabled', models.BooleanField(default=False, verbose_name='')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(verbose_name='')),
                ('text', models.TextField(verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='')),
                ('is_read', models.BooleanField(default=False, verbose_name='')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('transaction_type', models.CharField(choices=[('1', 'Cancellation'), ('2', 'Deposit'), ('3', 'Payment'), ('4', 'Others'), ('5', 'Order refusal')], default='1', max_length=20)),
                ('amount', models.FloatField(default=0, verbose_name='')),
            ],
        ),
    ]
