# Generated by Django 4.1.6 on 2023-02-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
    ]
