# Generated by Django 4.1.6 on 2023-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_address_is_deleted_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
