# Generated by Django 4.1.6 on 2023-03-12 09:03

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='')),
                ('is_read', models.BooleanField(default=False, verbose_name='')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='')),
                ('sender', models.OneToOneField(default=customer.models.Message.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
