# Generated by Django 4.1.6 on 2023-03-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'Cancellation'), ('2', 'Deposit'), ('3', 'Payment'), ('4', 'Others'), ('5', 'Order refusal')], default='1', max_length=20),
        ),
    ]
