# Generated by Django 4.1.6 on 2023-03-12 09:31

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_order_status'),
        ('customer', '0008_alter_wallet_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=customer.models.Message.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
