# Generated by Django 4.1.6 on 2023-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_wallet_order_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='heading',
            field=models.TextField(default='Test heading', verbose_name=''),
            preserve_default=False,
        ),
    ]
